### ISSUE TITLE
There are some images in the dataset that have deviated labels.

### ISSUE THREAD

**Issue by winter2897** [R3ab/ttpla_dataset#1]
Hi @R3ab, 
There are some images in the dataset that have deviated labels. How can I fix them?
![Screenshot from 2021-03-26 14-14-43](https://user-images.githubusercontent.com/22476495/112596089-eae5a580-8e3d-11eb-9a5e-3ccf55e3f74a.png)

**Comment by R3ab** [comment]
I will fix this image and update the dataset very soon. If you notice this issue in more than one image, please let me know the number of images.

**Comment by winter2897** [comment]
@R3ab  Only 2 images: 76_3795.jpg and 76_3810.jpg

**Comment by R3ab** [comment]
you can access the updated source of dataset.

**Comment by winter2897** [comment]
thank you!
