### ISSUE TITLE
Resize image script has a problem

### ISSUE THREAD

**Issue by winter2897** [R3ab/ttpla_dataset#2]
## Resize image script has a problem
Hi @R3ab,
Can you give me some advice?

## Resize command
```
python ./scripts/resize_image_and_annotation-final.py -t ./images
```
## Sized_data Folder

Images have been resized!

![Screenshot from 2021-03-30 16-52-49](https://user-images.githubusercontent.com/22476495/112970420-60bc7a80-9178-11eb-8709-7bd57fd30ab4.png)

## View on labelme

But, when I show dataset on `labelme`.

![Screenshot from 2021-03-30 16-47-56](https://user-images.githubusercontent.com/22476495/112970016-f9062f80-9177-11eb-8ca4-c72c613938c7.png)

## Labelme Error Logs

```
[ERROR  ] label_file:_check_image_height_and_width:160 - imageWidth does not match with imageData or imagePath, so getting imageWidth from actual image.
```

## reason
I think this error is caused by the `` "imageData" `` in the `.json` file of the image is encrypted.

**Comment by R3ab** [comment]
This script resize the polygon and update the imageWidth and imagePath. However, it does not update the hash of the image in the json file. So, when you open the json file in labelme, it reads the hashed image with its original size and loads the polygons with the resized one.

So, if you want to visualize this, you can write script to load the resized polygon on resized images or update the hash image in the json file.

**Comment by winter2897** [comment]
Thank you!
