### ISSUE TITLE
the weight link of yolact_img640_secondval_399_30000_resnet50.pth   is error?

### ISSUE THREAD

**Issue by aricojf** [R3ab/ttpla_dataset#3]
hi,everybody
i want to download the default weight file of the image size 640*360,backbone is rest50,hi,
when i download the weight file link,i find the fact file is yolact_img700_399_45100_resnet101_b8.pth in google driver,but the label is yolact_img640_secondval_399_30000_resnet50.pth , please tell me ,is it ok?

**Comment by R3ab** [comment]
The file is updated. Thank you!

**Comment by R3ab** [comment]
The file is updated. Thank you!

**Comment by R3ab** [comment]
I will close this issue. Please let me know if you have another concern.

**Comment by Barry-Liang** [comment]
The weight link to yolact_img640_secondval_399_30000_resnet101.pth is also wrong.
