### ISSUE TITLE
Unable to extract images

### ISSUE THREAD

**Issue by EmmanouelP** [R3ab/ttpla_dataset#4]
When I try to unzip the .zip file downloaded from your google drive link it says that the file is corrupted and therefore can't extract the images and annotations. Is there something wrong with the file or is it just me?

**Comment by R3ab** [comment]
please share with me a google drive link and I can upload it directly.

**Comment by daniperfer** [comment]
Hi, I've got the same problem than @EmmanouelP: after downloading the dataset from the google drive link, I cannot extract data since it says that the file is corrupted. Could I also use an alternative way for downloading it?

**Comment by EmmanouelP** [comment]
I was able to download and extract the images from Windows. This "corrpuption" seems to appear when you download the files from Linux systems. Alternatively you can share a google drive link to @R3ab so he could upload them directly.

**Comment by daniperfer** [comment]
Thanks for replying. I was also able to download and extract the images from Windows.
For Linux, I've finally found a way to extract the apparently "corrupted" files. The next steps worked for me (based on what is said here: https://superuser.com/questions/23290/terminal-tool-linux-for-repair-corrupted-zip-files):
```
    zip -FF data_original_size_v1.zip ttpla01.zip
    zip -FF ttpla01.zip ttpla02.zip
    unzip ttpla02.zip -d TTPLA/
```
